using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Carmen.Desktop.Properties
{
    /// <summary>
    /// Based on the autogenerated Settings class
    /// </summary>
    internal sealed class Widths : OnlyJsonApplicationSettingsBase
    {
        private static Widths defaultInstance = (Widths)Synchronized(new Widths());

        public static Widths Default => defaultInstance;

        private Widths()
        {
            RegisterJsonProperty(nameof(AllocateRolesGrid), () => AllocateRolesGrid, o => {
                o.DefaultValue = double.NaN; // NaN means "Auto"
                AllocateRolesGrid = o;
            });
        }

        /// <summary>The width in pixels of columns in the AllocateRoles grid view</summary>
        public OmnificentDictionary<string, double> AllocateRolesGrid { get; private set; } = null!;

        public void ClearAllocateRolesGrid()
        {
            AllocateRolesGrid = new()
            {
                DefaultValue = double.NaN // NaN means "Auto"
            };
        }
    }
}
