using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CarmenUI.Properties
{
    /// <summary>
    /// Based on the autogenerated Settings class
    /// </summary>
    internal sealed class Imports : OnlyJsonApplicationSettingsBase
    {
        private static Imports defaultInstance = (Imports)Synchronized(new Imports());

        public static Imports Default => defaultInstance;

        private Imports()
        {
            RegisterJsonProperty(nameof(ColumnMappings), () => ColumnMappings, o => ColumnMappings = o);
            RegisterJsonProperty(nameof(MatchingColumns), () => MatchingColumns, o => MatchingColumns = o);
        }

        /// <summary>Lookup from InputColumn header to ImportColumn name</summary>
        public Dictionary<string, string> ColumnMappings { get; private set; } = null!;

        /// <summary>Lookup from ImportColumn name to MatchExisting flag</summary>
        public Dictionary<string, bool> MatchingColumns { get; private set; } = null!;

        public void ClearImportSettings()
        {
            ColumnMappings = new();
            MatchingColumns = new();
        }
    }
}
