using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CarmenUI.Properties
{
    /// <summary>
    /// Based on the autogenerated Settings class
    /// </summary>
    internal sealed class Imports : ApplicationSettingsBase
    {
        private static Imports defaultInstance = (Imports)Synchronized(new Imports());

        public static Imports Default => defaultInstance;

        private Imports()
        {
            ColumnMappings ??= new();
            MatchingColumns ??= new();
        }

        /// <summary>Lookup from InputColumn header to ImportColumn name</summary>
        [UserScopedSetting]
        [SettingsSerializeAs(SettingsSerializeAs.Binary)]
        public Dictionary<string, string> ColumnMappings
        {
            get => (Dictionary<string, string>)this[nameof(ColumnMappings)];
            private set => this[nameof(ColumnMappings)] = value;
        }

        /// <summary>Lookup from ImportColumn name to MatchExisting flag</summary>
        [UserScopedSetting]
        [SettingsSerializeAs(SettingsSerializeAs.Binary)]
        public Dictionary<string, bool> MatchingColumns
        {
            get => (Dictionary<string, bool>)this[nameof(MatchingColumns)];
            private set => this[nameof(MatchingColumns)] = value;
        }

        public void ClearImportSettings() //TODO add a clear button to SettingsWindow
        {
            ColumnMappings = new();
            MatchingColumns = new();
        }
    }
}
