using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;

namespace CarmenUI.Properties
{
    /// <summary>
    /// Based on the autogenerated Settings class
    /// </summary>
    internal sealed class Timings : JsonApplicationSettings
    {
        private static Timings defaultInstance = (Timings)Synchronized(new Timings());

        public static Timings Default => defaultInstance;

        private Timings()
        {
            TotalTime = LoadJson<Dictionary<string, int>>(Json_TotalTime);
            SubSegments = LoadJson<Dictionary<string, string[]>>(Json_SubSegments);
        }

        protected override void UpdateJsonStrings()
        {
            Json_TotalTime = StoreJson(TotalTime);
            Json_SubSegments = StoreJson(SubSegments);
        }

        /// <summary>The total milliseconds taken for a segment with the given key</summary>
        public Dictionary<string, int> TotalTime { get; private set; }

        [UserScopedSetting]
        public string Json_TotalTime
        {
            get => (string)this[nameof(Json_TotalTime)];
            private set => this[nameof(Json_TotalTime)] = value;
        }

        /// <summary>A list of sub-segments within the segment of the given key</summary>
        public Dictionary<string, string[]> SubSegments { get; private set; }

        [UserScopedSetting]
        public string Json_SubSegments
        {
            get => (string)this[nameof(Json_SubSegments)];
            private set => this[nameof(Json_SubSegments)] = value;
        }

        public void ClearTimings()
        {
            TotalTime = new();
            SubSegments = new();
        }
    }
}
