using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;

namespace CarmenUI.Properties
{
    /// <summary>
    /// Based on the autogenerated Settings class
    /// </summary>
    internal sealed class Timings : JsonApplicationSettings
    {
        private static Timings defaultInstance = (Timings)Synchronized(new Timings());

        public static Timings Default => defaultInstance;

        private Timings()
        {
            RegisterJsonProperty(nameof(TotalTime), () => TotalTime, o => TotalTime = o);
            RegisterJsonProperty(nameof(SubSegments), () => SubSegments, o => SubSegments = o);
        }

        [UserScopedSetting]
        public object? _generateProvider => null;

        /// <summary>The total milliseconds taken for a segment with the given key</summary>
        public Dictionary<string, int> TotalTime { get; private set; } = null!;

        /// <summary>A list of sub-segments within the segment of the given key</summary>
        public Dictionary<string, string[]> SubSegments { get; private set; } = null!;

        public void ClearTimings()
        {
            TotalTime = new();
            SubSegments = new();
        }
    }
}
