using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CarmenUI.Properties
{
    /// <summary>
    /// Based on the autogenerated Settings class
    /// </summary>
    internal sealed class Timings : ApplicationSettingsBase
    {
        private static Timings defaultInstance = (Timings)Synchronized(new Timings());

        public static Timings Default => defaultInstance;

        private Timings()
        {
            TotalTime ??= new();
            SubSegments ??= new();
        }

        /// <summary>The total milliseconds taken for a segment with the given key</summary>
        [UserScopedSetting]
        [SettingsSerializeAs(SettingsSerializeAs.Binary)]
        public Dictionary<string, int> TotalTime
        {
            get => (Dictionary<string, int>)this[nameof(TotalTime)];
            private set
            {
                this[nameof(TotalTime)] = value;
            }
        }

        /// <summary>A list of sub-segments within the segment of the given key</summary>
        [UserScopedSetting]
        [SettingsSerializeAs(SettingsSerializeAs.Binary)]
        public Dictionary<string, string[]> SubSegments
        {
            get => (Dictionary<string, string[]>)this[nameof(SubSegments)];
            private set
            {
                this[nameof(SubSegments)] = value;
            }
        }

        public void ClearTimings()
        {
            TotalTime = new();
            SubSegments = new();
        }
    }
}
