using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CarmenUI.Properties
{
    /// <summary>
    /// Based on the autogenerated Settings class
    /// </summary>
    internal sealed class Widths : ApplicationSettingsBase
    {
        private static Widths defaultInstance = (Widths)Synchronized(new Widths());

        public static Widths Default => defaultInstance;

        private Widths()
        {
            AllocateRolesGridRaw ??= new();
            AllocateRolesGrid = new(AllocateRolesGridRaw, double.NaN); // NaN means "Auto"
        }

        public OmnificentDictionaryWrapper<string, double> AllocateRolesGrid { get; init; }

        /// <summary>The width in pixels of columns in the AllocateRoles grid view</summary>
        [UserScopedSetting]
        [SettingsSerializeAs(SettingsSerializeAs.Binary)]
        public Dictionary<string, double> AllocateRolesGridRaw
        {
            get => (Dictionary<string, double>)this[nameof(AllocateRolesGridRaw)];
            init => this[nameof(AllocateRolesGridRaw)] = value;
        }
    }
}
